spring:
  cloud:
    azure:
      storage:
        container-name: blob-file-io
        account-key: ${ACCOUNT_KEY:fake123==}
        account-name: azwepersonal0001
        endpoint: https://azwepersonal0001.blob.core.windows.net/blob-file-io
