spring:
  cloud:
    azure:
      storage:
        blob:
          account-key: ${ACCOUNT_KEY:fake123==}
          account-name: azwepersonal0001
          container-name: blob-file-io
          endpoint: https://azwepersonal0001.blob.core.windows.net/blob-file-io
